import { RecipeCategory } from '@api/types';

export const CATEGORY_LABELS: Record<RecipeCategory, string> = {
  breakfast: 'Breakfast',
  lunch: 'Lunch',
  dinner: 'Dinner',
  snacks: 'Snacks',
  appetizers: 'Appetizers',
  'soups-stews': 'Soups & Stews',
  salads: 'Salads',
  sides: 'Sides',
  'flatbreads-breads': 'Flatbreads & Breads',
  'pastries-doughs': 'Pastries & Doughs',
  'pasta-noodles': 'Pasta & Noodles',
  'rice-grains': 'Rice & Grains',
  'meat-dishes': 'Meat Dishes',
  'seafood-dishes': 'Seafood Dishes',
  'vegetarian-mains': 'Vegetarian Mains',
  'vegan-mains': 'Vegan Mains',
  desserts: 'Desserts',
  'cakes-muffins': 'Cakes & Muffins',
  'cookies-bars': 'Cookies & Bars',
  'drinks-smoothies': 'Drinks & Smoothies',
  'sauces-condiments': 'Sauces & Condiments',
  'spice-mixes-marinades': 'Spice Mixes & Marinades',
};

export const TAGS = {
  cuisine: [
    'Indian',
    'Italian',
    'Middle Eastern',
    'Mexican',
    'Thai',
    'Japanese',
    'Greek',
    'French',
    'American',
    'Korean',
    'Spanish',
    'Mediterranean',
  ],
  dietary: [
    'Vegan',
    'Vegetarian',
    'Gluten-Free',
    'Dairy-Free',
    'Keto',
    'Low-Carb',
    'Paleo',
    'Nut-Free',
  ],
  method: ['Baked', 'Fried', 'Grilled', 'Steamed', 'Raw', 'Roasted', 'Air Fryer', 'Slow Cooker'],
  occasion: [
    'Breakfast',
    'Brunch',
    'Dinner Party',
    'Holiday',
    'Quick Meal',
    'Meal Prep',
    'Kids Friendly',
  ],
  time: ['15-Minute', '30-Minute', 'One-Pot'],
} as const;

export const MEASURING_UNITS = {
  volume: ['mL', 'L', 'tsp', 'tbsp', 'fl oz', 'cup', 'pint', 'quart', 'gallon'],
  weight: ['g', 'kg', 'oz', 'lb'],
  count: ['piece', 'slice', 'clove', 'leaf', 'pinch', 'dash'],
  temperature: ['°C', '°F'],
} as const;

export const MEASURING_UNITS_ALL = [
  'mL',
  'L',
  'tsp',
  'tbsp',
  'fl oz',
  'cup',
  'pint',
  'quart',
  'gallon',
  'g',
  'kg',
  'oz',
  'lb',
  'piece',
  'slice',
  'clove',
  'leaf',
  'pinch',
  'dash',
];
